---
- name: Create a recurring cron job run by user Natasha
  hosts: dev

  tasks:
    - name: Create a cron job 
      cron:
        name: A date and time collection job
        job: date >> /home/natasha/add_date_time_cron_job
        minute: "*/2"
        hour: 9-16
        weekday: 1-5
        user: natasha
        cron_file: add_date_time
        state: present
