---
- name: Create a Logical Volume on research volume group
  hosts: all
  ignore_errors: yes

  vars:
    vg_name: research
    lv_name: data
    lv_size: "1500m"

  tasks:
    - name: Verify whether research volume group is present
      command: vgs "{{ vg_name }}"
      changed_when: false
      register: vg_status

    - name: Display status of research volume
      debug: 
        msg: "Volume group does not exist"
      when: vg_status is failed

    - name: Create a logical volume
      lvol:
        vg: "{{ vg_name }}"
        lv: "{{ lv_name }}"
        size: "{{ lv_size }}"
      when: vg_status is not failed
      register: lv_status

    - name: Display status of logical volume
      debug:
        msg: "Requested logical volume size cannot be created. 800MiB should be used instead"
      when: lv_status is failed and '"insufficient free space" in lv_status.err'
      
    - name: Format the logical volume with ext4
      filesystem:
        fstype: ext4
        dev: /dev/{{ vg_name }}/{{ lv_name }}
      when: vg_status is not failed and lv_status is not failed
